stages:
  - lint
  - build
  - test
  - deploy

sonarqube:
  stage: lint
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner -Dsonar.projectKey=flask-app -Dsonar.sources=. -Dsonar.host.url=http://192.168.31.170:9000 -Dsonar.login=$SONARQUBE_TOKEN
  only:
    - main

lint:
  stage: lint
  image: node:16
  script:
    - npm install -g eslint
    - eslint app.py

build:
  stage: build
  image: docker:20.10.7
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t flask-app .

stages:
  - test

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - pytest

deploy:
  stage: deploy
  script:
    - docker-compose up -d
