name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disable shallow clone for better relevancy of analysis

      - name: Checkout external repository 
        uses: actions/checkout@v4
        with:
          repository: fportantier/vulpy
          path: external-vulpy

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          sonar-project-key: "mytest"
          sonar-project-name: "MyTestProject"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

